### ISSUE TITLE
See more and See Less not showing up

### ISSUE THREAD

**Issue by prameetc** [kashishgrover/react-native-see-more-inline#1]
![Simulator Screen Shot - iPhone 8 Plus - 2020-04-21 at 12 57 55](https://user-images.githubusercontent.com/13821323/79837867-bb2d5280-83cf-11ea-9651-8b61c8d2da19.png)

I tried to use the example project and not able to see the "See More" and "See Less" option, am I doing something wrong?

**Comment by fliklab** [comment]
I am using this plugin in two RN projects. It works fine in one app. But it doesn't work well in another app as your screenshot. Both codes are almost identical and I can't find the reason why it dosen' t work. The difference is the react-native version. The working project is version 0.62, what doesn't work is 0.61.5

**Comment by 1ike** [comment]
Cuz dependency react-native-text-size does not work as I understood. I think we can forget about these packages. :(

**Comment by kashishgrover** [comment]
Hey guys, I’ve been pretty busy over the past couple of months. I will release an update for this very soon, and update the docs with my latest findings as well. Apologies for the delay

**Comment by kashishgrover** [comment]
@prameetc @fliklab @1ike I just pushed v1.2.0 to npm. Can you folks try it out and give feedback? I'll keep this issue open till we solve this for good. Thanks!

**Comment by 1ike** [comment]
Still have the error "Cannot read property 'measure' of undefined". It was predictable cuz "react-native-text-size" still in use.
"react-native-text-size" may be has problem with Expo (Expo 36 in my case).

**Comment by kashishgrover** [comment]
@1ike In my knowledge, there is no package like `react-native-text-size` that can work for expo. Since that package links natively, it won't work with an expo managed workflow. You will have to eject the project or use a barebones react native project for that.
To calculate the width of a text, we need to use this package. If you find any alternative which will help us get rid of this dependency, do suggest. All we need to do here is accurately calculate the width of the text.

**Comment by 1ike** [comment]
I think will be usefull to write in Readme about this.

**Comment by kashishgrover** [comment]
You're right, I'll do that. Thanks!

**Comment by fliklab** [comment]
Thank you for updates! It is now working well.
 
And I found something different from before: 
If there is a line break in the text, it works to break the text right there and display 'see more'.
Previously, there was a case where 'see more' was not displayed when there was a line break, so it seems to be an improvement. However, it seems not intended when there is a line-break in a position less than the max-number of lines, 'see more' is displayed from there.

**Comment by kashishgrover** [comment]
@fliklab Thanks for testing it. I’m glad it is better now. 
Regarding the line break thing, it was something I added as per my use case in my project. There could be edge cases remaining. Feel free to make another issue on this repo with some screenshots of the text before and after clicking “see more” and we can have a discussion over there.

**Comment by mehdinourollah** [comment]
I'm having this issue ( not showing the Show More and Show less) but in React Native CLI and not expo 
`   "react": "16.13.1",
    "react-native": "0.63.4",
  "react-native-text-size": "^4.0.0-rc.1",
"react-native-see-more-inline": "^1.3.0",`

![image](https://user-images.githubusercontent.com/5097056/104711440-6fc38d00-5732-11eb-95fc-b92beab3cdce.png)

**Comment by kashishgrover** [comment]
@mehdinourollah can you verify if the `react-native-text-size` package got installed correctly? It should have a folder in your project's `node_modules` folder.

https://github.com/kashishgrover/react-native-see-more-inline/blob/cbcffb27535ce8962f94fc48a2c422484d2cf16f/src/SeeMore/SeeMoreUtil.js#L33

**Comment by mehdinourollah** [comment]
Sorry It's working with react-native-text-size now ...It needed a clean android and starting over to react-native-text-size install it's native modules...Thank you so much for this great plugin bro

**Comment by cloudorbush** [comment]
Has anybody tried if this library works now with expo dev-client?

**Comment by dryprogrammer** [comment]
I'm still getting this error. https://github.com/aMarCruz/react-native-text-size/pull/39 was supposed to fix the native linking

**Comment by dryprogrammer** [comment]
https://github.com/benjaminharringtonrose/react-native-text-dimensions/blob/master/react-native.config.js approach also seems to work with react-native.config.js

**Comment by dryprogrammer** [comment]
I just used https://www.npmjs.com/package/@duonghaidang/react-native-text-more for now
